testing

diff --git a/app/make-timeavgs/bin/make-timeavgs b/app/make-timeavgs/bin/make-timeavgs
--- a/app/make-timeavgs/bin/make-timeavgs
+++ b/app/make-timeavgs/bin/make-timeavgs
@@ -5,6 +5,15 @@ set -euo pipefail
 # use fre-python-tools generate_time_average module to average history files 
 #
 
+echo "[COLE] this is a test"
+echo "module load python..."
+module load python
+echo "module load fre-nctools..."
+module load fre-nctools
+export input_file_list=
+export output_file_list=
+echo "[COLE] created i/o lists"
+
 echo Arguments:
 echo "    cycle point: $CYLC_TASK_CYCLE_POINT"
 echo "    input dir: $inputDir"
@@ -33,13 +42,13 @@ for dir in ${dirs[@]}; do
 	echo "---DEBUG--- FOUND dir: $dir"	
 	echo "looking at directory structure file frequency..."
 
-    # retrieve the regrid resolution subtype
-    if [[ $use_subdirs ]]; then
-        pushd $dir
-        cd ../..
-        subdir=$(basename $(pwd))
-        popd
-    fi
+	# retrieve the regrid resolution subtype
+	if [[ $use_subdirs ]]; then
+		pushd $dir
+		cd ../..
+		subdir=$(basename $(pwd))
+		popd
+	fi
 
 	# check file frequency via directory name
 	file_freq=${dir##*/}
@@ -67,48 +76,69 @@ for dir in ${dirs[@]}; do
 
 	debugCount=0
 	for file in ${files[@]}; do
-        # reduce date precision of output name to year-only,
-        # and include only one year if a one-year interval
-        basename=$(basename $file)
-        date1=$(echo $basename | cut -d. -f2 | cut -d- -f1)
-        date2=$(echo $basename | cut -d. -f2 | cut -d- -f2)
-        date1=${date1:0:4}
-        date2=${date2:0:4}
-        var=$(echo $basename | cut -d. -f3)
-        if (( $(echo $basename | grep -o '\.' | wc -l) == 4 )); then
-            tile=$(echo $basename | cut -d. -f4)
-        else
-            tile=""
-        fi
-        if [[ $date1 == $date2 ]]; then
-            if [[ -n $tile ]]; then
-                newfile=$component.$date1.$var.$tile.nc
-            else
-                newfile=$component.$date1.$var.nc
-            fi
-        else
-            if [[ -n $tile ]]; then
-                newfile=$component.$date1-$date2.$var.$tile.nc
-            else
-                newfile=$component.$date1-$date2.$var.nc
-            fi
-        fi
+        	# reduce date precision of output name to year-only,
+        	# and include only one year if a one-year interval
+        	basename=$(basename $file)
+		export input_file_list=${input_file_list}$(shasum -a 512256 $file),
+		echo "[COLE] added ${file} to input list"
+		echo "[COLE] basename : ${basename}"
+        	date1=$(echo $basename | cut -d. -f2 | cut -d- -f1)
+        	date2=$(echo $basename | cut -d. -f2 | cut -d- -f2)
+        	date1=${date1:0:4}
+        	date2=${date2:0:4}
+        	var=$(echo $basename | cut -d. -f3)
+        	if (( $(echo $basename | grep -o '\.' | wc -l) == 4 )); then
+            		tile=$(echo $basename | cut -d. -f4)
+		else
+        	    tile=""
+        	fi
+        	if [[ $date1 == $date2 ]]; then
+            		if [[ -n $tile ]]; then
+                		newfile=$component.$date1.$var.$tile.nc
+            		else
+                		newfile=$component.$date1.$var.nc
+            		fi
+        	else
+            		if [[ -n $tile ]]; then
+                		newfile=$component.$date1-$date2.$var.$tile.nc
+            		else
+                		newfile=$component.$date1-$date2.$var.nc
+            		fi
+        	fi
 
-        if [[ $use_subdirs ]]; then
-            output_dir=$outputDir/$subdir/$component/$file_freq/$interval
-        else
-            output_dir=$outputDir/$component/$file_freq/$interval
-        fi
+        	if [[ $use_subdirs ]]; then
+            		output_dir=$outputDir/$subdir/$component/$file_freq/$interval
+        	else
+            		output_dir=$outputDir/$component/$file_freq/$interval
+        	fi
+
+		output_file=${output_dir}/$newfile
 		mkdir -p $output_dir
-        cmd="generate-time-averages -p cdo -a $tool_args ${file} ${output_dir}/$newfile"
-        echo "---DEBUG--- to run: $cmd"
+        	cmd="generate-time-averages -p cdo -a $tool_args ${file} ${output_file}"
+	        
+		echo "---DEBUG--- to run: $cmd"
 		
 		if ! $cmd; then
-		    echo "---ERROR--- Failed: timeaverage: $cmd"
-            exit $?
-        fi
+			echo "---ERROR--- Failed: timeaverage: $cmd"
+            		exit $?
+        	fi
+
+		export output_file_list=${output_file_list}$(shasum -a 512256 $output_file),
+                echo "[COLE] added ${output_file} to output list"
+                echo "[COLE] output file = ${output_dir} + ${newfile}"
+
 	done
 	
 done
+
+echo "[COLE] epmt analysis and annotate"
+which epmt
+echo -e "\n---input---"
+echo -e "epmt annotate DATA_LINEAGE_IN = \n	${input_file_list%*,}"
+epmt annotate EPMT_DATA_LINEAGE_IN="${input_file_list%*,}"
+
+echo -e "\n---output---"
+echo -e "epmt annotate DATA_LINEAGE_OUT = \n	${output_file_list%*,}"
+epmt annotate EPMT_DATA_LINEAGE_OUT="${output_file_list%*,}"
 
 exit 0
