add more test calls to apps/scripts that have them. exit status guards for most. expecting to likely not have all the req deps

diff --git a/.github/workflows/create_test_conda_env.yml b/.github/workflows/create_test_conda_env.yml
--- a/.github/workflows/create_test_conda_env.yml
+++ b/.github/workflows/create_test_conda_env.yml
@@ -30,9 +30,18 @@ jobs:
         run: |
           # try to make sure the right things are in GITHUB_PATH
           echo $CONDA/envs/fre-workflows/bin >> $GITHUB_PATH
+
           # lint .cylc workflow files
           cylc lint -v || echo "cylc lint threw non-zero exit code"
+
           # unittests for data_lineage
-          cd data_lineage && python -m unittest discover -s test -v; cd -
+          cd data_lineage && python -m unittest discover -s test -v; cd -;
+
           # pytest unittests for make-timeseries
-          cd app/make-timeseries && pytest -v -v -x ./tests/; cd -
+          cd app/make-timeseries && pytest -v -v -x ./tests/ || echo "pytest for make-timeseries failed"; cd -;
+
+          # pytest unittests for remap-pp-components
+          cd app/remap-pp-components && pytest -v -v -x ./t/ || echo "pytest for remap-pp-components failed"; cd -;
+
+          # pytest unittests for other things in this repository
+          pytest -v -v -x ./tests;
