#245 add yaml anchor with script to run for each task

diff --git a/.github/workflows/test_cloud_runner.yml b/.github/workflows/test_cloud_runner.yml
--- a/.github/workflows/test_cloud_runner.yml
+++ b/.github/workflows/test_cloud_runner.yml
@@ -57,6 +57,35 @@ jobs:
           echo "fre-cli repo: $(git remote -v)"
           echo "fre-cli branch: $(git branch)"
           cd -
+      - name: Reusable check
+        run: &task_check |
+          set +e
+          # Successes
+          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/$TASK_NAME/0[1-3]/job.status)
+          exit_status_1=$?                                                                                                                   
+          # Failures
+          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/$TASK_NAME/0[1-3]/job.status)
+          exit_status_2=$?
+
+          if [ $exit_status_1 -eq 0 ]; then
+              echo $success | sed 's/ /\n/g' #split string by spaces
+          elif [ $exit_status_1 -eq 1 ]; then
+              echo "No succeeded tasks found"
+          else
+              echo "WARNING: error with grep execution"
+              exit 2
+          fi
+
+          if [ $exit_status_2 -eq 0 ]; then
+              echo "Failures found"
+              echo $failure | sed 's/ /\n/g' #split string by spaces
+              exit 1   #exit with error
+          elif [ $exit_status_2 -eq 1 ]; then
+              echo "No task failures found."
+          else
+              echo "WARNING: error with grep execution"
+              exit 2
+          fi
       - name: Run ppp-container
         run: |
           # Print pwd then run script
@@ -105,346 +134,60 @@ jobs:
           echo ""
 
       - name: Print pp-starter successes or failures
-        run: |
-          set +e
-          # Successes
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/pp-starter/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/pp-starter/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env: 
+          TASK_NAME: "pp-starter"
+        run: *task_check
 
       - name: Print stage-history successes or failures
-        run: |
-          set +e
-          # Successes 
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "stage-history"
+        run: *task_check 
 
       - name: Print regrid-xy successes or failures
-        run: |
-          set +e
-          # Successes 
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "regrid-xy*"
+        run: *task_check
 
       - name: Print data-catalog-final (FAILURE-GUARDED)
         continue-on-error: true
-        run: |
-          set +e
-          # Successes 
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/data-catalog-final/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/data-catalog-final/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "data-catalogi-final"
+        run: *task_check
 
       - name: Print  mask-atmos-plevel successes or failures
-        run: |
-          set +e
-          # Successes
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/mask-atmos-plevel*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/mask-atmos-plevel*/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "mask-atmos-plevel*"
+        run: *task_check
 
       - name: Print remap-pp-components successes or failures
-        run: |
-          set +e
-          # Successes 
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "remap-pp-components*"
+        run: *task_check
 
       - name: Print split-netcdf successes or failures
-        run: |
-          set +e
-          # Successes 
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf*/0[1-3]/job.status)
-          exit_status_2=$? 
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "split-netcdf*"
+        run: *task_check
 
       - name: Print climotology time average successes or failures
-        run: |
-          set +e
-          # Successes 
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/climo-*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/climo-*/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "climo-*"
+        run: *task_check
 
       - name: Print combine-climo successes or failures
-        run: |
-          set +e
-          # Successes 
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-climo-*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-climo*/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "combine-climo-*"
+        run: *task_check
 
       - name: Print remap-climo successes or failures
-        run: |
-          set +e
-          # Successes 
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-climo-*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-climo-*/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "remap-climo-*"
+        run: *task_check
 
       - name: Print clean task successes or failures
-        run: |
-          set +e
-          # Successes
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/clean*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/clean*/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
+        env:
+          TASK_NAME: "clean*"
+        run: *task_check
 
 ## Keep in here for now as a just in case reference ##
 #      - name: Print any succeeded tasks
