#216 add testfor refineDiag task in pipeline

diff --git a/.github/workflows/test_cloud_runner.yml b/.github/workflows/test_cloud_runner.yml
--- a/.github/workflows/test_cloud_runner.yml
+++ b/.github/workflows/test_cloud_runner.yml
@@ -195,41 +195,42 @@ jobs:
               echo "WARNING: error with grep execution"
               exit 2
           fi
-#      - name: Print refine-diag successes or failures
-#        run: |
-#          set +e
-#          # Successes 
-#          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/REFINE-DIAG/0[1-3]/job.status)
-#          exit_status_1=$?
-#
-#          # Failures
-#          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/REFINE-DIAG/0[1-3]/job.status)
-#          exit_status_2=$?
-#
-#          if [ $exit_status_1 -eq 0 ]; then
-#              echo $success | sed 's/ /\n/g' #split string by spaces
-#
-#              # Check if refine-diag task executed correctly
-#              # history files copied into another history file 
-#              # ........
-#
-#          elif [ $exit_status_1 -eq 1 ]; then
-#              echo "No succeeded tasks found"
-#          else
-#              echo "WARNING: error with grep execution"
-#              exit 2
-#          fi
-#
-#          if [ $exit_status_2 -eq 0 ]; then
-#              echo "Failures found"
-#              echo $failure | sed 's/ /\n/g' #split string by spaces
-#              exit 1   #exit with error
-#          elif [ $exit_status_2 -eq 1 ]; then
-#              echo "No task failures found."
-#          else
-#              echo "WARNING: error with grep execution"
-#              exit 2
-#          fi
+
+      - name: Print refine-diag successes or failures
+        run: |
+          set +e
+          # Successes 
+          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/refineDiag-*/0[1-3]/job.status)
+          exit_status_1=$?
+
+          # Failures
+          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib-efs/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/refineDiag-*/0[1-3]/job.status)
+          exit_status_2=$?
+
+          if [ $exit_status_1 -eq 0 ]; then
+              echo $success | sed 's/ /\n/g' #split string by spaces
+
+              # Check if refine-diag task executed correctly
+              # history files copied into another history file 
+              # ........
+
+          elif [ $exit_status_1 -eq 1 ]; then
+              echo "No succeeded tasks found"
+          else
+              echo "WARNING: error with grep execution"
+              exit 2
+          fi
+
+          if [ $exit_status_2 -eq 0 ]; then
+              echo "Failures found"
+              echo $failure | sed 's/ /\n/g' #split string by spaces
+              exit 1   #exit with error
+          elif [ $exit_status_2 -eq 1 ]; then
+              echo "No task failures found."
+          else
+              echo "WARNING: error with grep execution"
+              exit 2
+          fi
 
       - name: Print pre-analysis successes or failures
         run: |
