add make-timeseries task status printout to workflow file, also clean up some whitespace here/there

diff --git a/.github/workflows/test_cloud_runner.yml b/.github/workflows/test_cloud_runner.yml
--- a/.github/workflows/test_cloud_runner.yml
+++ b/.github/workflows/test_cloud_runner.yml
@@ -97,7 +97,7 @@ jobs:
       - name: Print stage-history successes or failures
         run: |
           set +e
-          # Successes 
+          # Successes
           success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/0[1-3]/job.status)
           exit_status_1=$?
 
@@ -129,7 +129,7 @@ jobs:
         continue-on-error: true
         run: |
           set +e
-          # Successes 
+          # Successes
           success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/0[1-3]/job.status)
           exit_status_1=$?
 
@@ -160,7 +160,7 @@ jobs:
       - name: Print remap-pp-components successes or failures
         run: |
           set +e
-          # Successes 
+          # Successes
           success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/0[1-3]/job.status)
           exit_status_1=$?
 
@@ -191,7 +191,7 @@ jobs:
       - name: Print make-timeavgs successes or failures
         run: |
           set +e
-          # Successes 
+          # Successes
           success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeavgs*/0[1-3]/job.status)
           exit_status_1=$?
 
@@ -222,9 +222,9 @@ jobs:
       - name: Print rename-split-to-pp successes or failures
         run: |
           set +e
-          # Successes 
+          # Successes
           success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/rename-split-to-pp*/0[1-3]/job.status)
-          exit_status_1=$? 
+          exit_status_1=$?
 
           # Failures
           failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/rename-split-to-pp*/0[1-3]/job.status)
@@ -253,13 +253,13 @@ jobs:
       - name: Print split-netcdf successes or failures
         run: |
           set +e
-          # Successes 
+          # Successes
           success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf*/0[1-3]/job.status)
           exit_status_1=$?
 
           # Failures
           failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf*/0[1-3]/job.status)
-          exit_status_2=$? 
+          exit_status_2=$?
 
           if [ $exit_status_1 -eq 0 ]; then
               echo $success | sed 's/ /\n/g' #split string by spaces
@@ -284,12 +284,44 @@ jobs:
       - name: Print combine-timeavgs successes or failures
         run: |
           set +e
-          # Successes 
+          # Successes
           success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/0[1-3]/job.status)
           exit_status_1=$?
 
           # Failures
           failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/0[1-3]/job.status)
+          exit_status_2=$?
+
+          if [ $exit_status_1 -eq 0 ]; then
+              echo $success | sed 's/ /\n/g' #split string by spaces
+          elif [ $exit_status_1 -eq 1 ]; then
+              echo "No succeeded tasks found"
+          else
+              echo "WARNING: error with grep execution"
+              exit 2
+          fi
+
+          if [ $exit_status_2 -eq 0 ]; then
+              echo "Failures found"
+              echo $failure | sed 's/ /\n/g' #split string by spaces
+              exit 1   #exit with error
+          elif [ $exit_status_2 -eq 1 ]; then
+              echo "No task failures found."
+          else
+              echo "WARNING: error with grep execution"
+              exit 2
+          fi
+
+      - name: Print make-timeseries successes or failures (STEP CONTINUES ON FAILURE)
+        continue-on-error: true
+        run: |
+          set +e
+          # Successes
+          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeseries*/0[1-3]/job.status)
+          exit_status_1=$?
+
+          # Failures
+          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeseries*/0[1-3]/job.status)
           exit_status_2=$?
 
           if [ $exit_status_1 -eq 0 ]; then
