fix pattern matching and exit status

diff --git a/.github/workflows/test_cloud_runner.yml b/.github/workflows/test_cloud_runner.yml
--- a/.github/workflows/test_cloud_runner.yml
+++ b/.github/workflows/test_cloud_runner.yml
@@ -46,119 +46,128 @@ jobs:
       - name: Print pp-starter successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/pp-starter/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/pp-starter/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/pp-starter/*/job.status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/pp-starter/0./job.status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/pp-starter/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/pp-starter/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines
+              echo "No failures found"
           fi
-          echo "No failures found"
 
       - name: Print stage-history successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/*/job/status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/0./job/status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/stage-history/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines
+              echo "No failures found"
           fi
-          echo "No failures found"
 
       - name: Print regrid-xy successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/*/job.status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/0./job.status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/regrid-xy*/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines
+              echo "No failures found"
           fi
-          echo "No failures found"
 
       - name: Print remap-pp-components successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/*/job.status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/0./job.status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/remap-pp-components*/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines
+              echo "No failures found"
           fi
-          echo "No failures found"
 
       - name: Print make-timeavgs successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeavgs*/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeavgs*/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeavgs*/*/job.status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeavgs*/0./job.status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeavgs*/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/make-timeavgs*/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines
+              echo "No failures found"
           fi
-          echo "No failures found"
 
       - name: Print rename-split-to-pp successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/rename-split-to-pp*/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/rename-split-to-pp*/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/rename-split-to-pp*/*/job.status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/rename-split-to-pp*/0./job.status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/rename-split-to-pp*/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/rename-split-to-pp*/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines
+              echo "No failures found"
           fi
-          echo "No failures found"
 
       - name: Print split-netcdf successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf*/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf*/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf**/*/job.status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf*/0./job.status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf**/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/split-netcdf*/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines
+              echo "No failures found"
           fi
-          echo "No failures found"
 
       - name: Print combine-timeavgs successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/*/job.status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/0./job.status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines 
+              echo "No failures found"
           fi
-          echo "No failures found"
 
       - name: Print clean task successes or failures
         run: |
           # Successes 
-          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/clean*/*/job.status
+          grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/clean*/0./job.status
 
           # Failures
-          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/clean*/*/job.status
+          grep -q -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/clean*/0./job.status
           if [ $? -eq 0 ]; then
-              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/clean*/*/job.status
+              grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/clean*/0./job.status
               exit 1
+          elif [ $? -eq 1]; then # grep exist status = 1 when it completed successfully but did not find any matching lines
+              echo "No failures found"
           fi
-          echo "No failures found"
 
 
 ## Keep in here for now as a just in case reference ##
