move around to test

diff --git a/.github/workflows/test_cloud_runner.yml b/.github/workflows/test_cloud_runner.yml
--- a/.github/workflows/test_cloud_runner.yml
+++ b/.github/workflows/test_cloud_runner.yml
@@ -157,6 +157,37 @@ jobs:
               exit 2
           fi
 
+      - name: Print  mask-atmos-plevel successes or failures
+        run: |
+          set +e
+          # Successes
+          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/mask-atmos-plevel*/0[1-3]/job.status)
+          exit_status_1=$?
+
+          # Failures
+          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/mask-atmos-plevel*/0[1-3]/job.status)
+          exit_status_2=$?
+
+          if [ $exit_status_1 -eq 0 ]; then
+              echo $success | sed 's/ /\n/g' #split string by spaces
+          elif [ $exit_status_1 -eq 1 ]; then
+              echo "No succeeded tasks found"
+          else
+              echo "WARNING: error with grep execution"
+              exit 2
+          fi
+
+          if [ $exit_status_2 -eq 0 ]; then
+              echo "Failures found"
+              echo $failure | sed 's/ /\n/g' #split string by spaces
+              exit 1   #exit with error
+          elif [ $exit_status_2 -eq 1 ]; then
+              echo "No task failures found."
+          else
+              echo "WARNING: error with grep execution"
+              exit 2
+          fi
+
       - name: Print remap-pp-components successes or failures
         run: |
           set +e
@@ -290,37 +321,6 @@ jobs:
 
           # Failures
           failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/combine-timeavgs*/0[1-3]/job.status)
-          exit_status_2=$?
-
-          if [ $exit_status_1 -eq 0 ]; then
-              echo $success | sed 's/ /\n/g' #split string by spaces
-          elif [ $exit_status_1 -eq 1 ]; then
-              echo "No succeeded tasks found"
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-          if [ $exit_status_2 -eq 0 ]; then
-              echo "Failures found"
-              echo $failure | sed 's/ /\n/g' #split string by spaces
-              exit 1   #exit with error
-          elif [ $exit_status_2 -eq 1 ]; then
-              echo "No task failures found."
-          else
-              echo "WARNING: error with grep execution"
-              exit 2
-          fi
-
-      - name: Print  mask-atmos-plevel successes or failures
-        run: |
-          set +e
-          # Successes
-          success=$(grep -E "CYLC_JOB_EXIT=SUCCEEDED" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/mask-atmos-plevel*/0[1-3]/job.status)
-          exit_status_1=$?
-
-          # Failures
-          failure=$(grep -E "CYLC_JOB_EXIT=ERR" /contrib/container-test/ppp-setup/cylc-run/test_pp__ptest__ttest/log/job/*/mask-atmos-plevel*/0[1-3]/job.status)
           exit_status_2=$?
 
           if [ $exit_status_1 -eq 0 ]; then
